Portfolio-details-popup-window
FaranoshAmini/Faranosh_Portfolio pull request #9
Opened 2022-06-15 09:31 UTC by FaranoshAmini

in this project I implemented the following interactions:
- When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
- When the user clicks (or taps) the close (X) button, the popup disappears.

I also implemented popups for both mobile and desktop screen sizes:
- Mobile popup
- I followed all project requirements.

2022-06-15 13:32 UTC, vechicin requested changes
# Hi @FaranoshAmini and @saqibjavaiddev ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Good job overall implementing the popup window

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-15 13:32 UTC, vechicin commented on style.css
> +}
Your design is not following the template design in either version.

Your design:

<img width="184" alt="Screen Shot 2022-06-15 at 8 26 19" src="https://user-images.githubusercontent.com/82426682/173838470-baa47218-86c2-48da-829c-5f18664c8c92.png">

<img width="1440" alt="Screen Shot 2022-06-15 at 8 26 47" src="https://user-images.githubusercontent.com/82426682/173838582-ea544d67-590d-4ded-8bd5-2495582f870f.png">

The template design:

<img width="213" alt="Screen Shot 2022-06-15 at 8 27 28" src="https://user-images.githubusercontent.com/82426682/173838741-95b6a0ad-f9d2-49a1-9e72-d9d9294f9752.png">

<img width="485" alt="Screen Shot 2022-06-15 at 8 27 52" src="https://user-images.githubusercontent.com/82426682/173838831-52206937-b3d3-49cc-bb1d-edbf3025edea.png">

Please fix it.

<img width="952" alt="Screen Shot 2022-06-15 at 8 28 31" src="https://user-images.githubusercontent.com/82426682/173838987-b0efdafa-7a42-4539-a29c-f935f5390f55.png">

2022-06-16 08:14 UTC, topeogunleye requested changes
> # Changes Required 
> ### Hi @FaranoshAmini,
> Nice job, you are almost there.
> 
> ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## (Highlights) Good Points: 
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please check my inline comment.
>- [ ] From now on, I kindly suggest that you please make use of imperative mood in the subject line for your commit messages.
:x: Wrong
![Screenshot from 2022-06-16 09-12-33](https://user-images.githubusercontent.com/52934128/174024621-0b51763e-6543-4af5-8730-1ca12ef4ad65.png)
> ### Good Commit Messages:
>- [x]  Add fix for dark mode toggle state
>- [x] Update README file.
>- [x] Add styles to h1.
>
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-16 08:14 UTC, topeogunleye commented on popup.js
> +function createMobileProjectCard(key) {
- [ ] As suggested by the previous code reviewer, I kindly suggest that your popup follows the design for both desktop and mobile versions from the chosen template in Figma (e.g., font, colours, images, tests, margins).

I can see that the colors for your *Microverse- Student* and *Web Developer • 2021* are wrong. please make use of the colors from your design template

2022-06-17 06:30 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @FaranoshAmini       , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

[OPTIONAL] Kindly add a screenshot to your README file showing your webpage user Interface. You can use extentions like fireshot to capturer the entire page.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-17 13:40 UTC, merged